@startuml diagrama-de-clases

'https://plantuml.com/class-diagram
' - private
' + public

' Part 1: Organizaciones y Miembros

enum TipoOrganizacion {
    GUBERNAMENTAL
    ONG
    EMPRESA
    INSTITUCION
}

class ClasificacionOrganizacion{
    - String nombre
}

class Organizacion {
    - String razonSocial
    - TipoOrganizacion tipo
    - Ubicacion ubicacion
    - List<Sector> sectores
    - ClasificacionOrganizacion clasificacion
    - List<DatosActividades> datosActividades
    - List<Contacto> contactos
    
    + boolean containsSector(sector)
    + void agregarSector(sector)
    + void aceptarVinculacionDeTrabajador(miembro, sector)
    + void cargarMediciones(String pathCSV)
    + List<DatosActividades> getDatosActividades()
    + List<Contacto> getContactos()
    + Localidad sectorLocalidad()
    + Municipio sectorMunicipio()
    + Provincia sectorProvincia()
    + void cargarDATransladoMiembros()
    + double calculoHCMensual()
    + HC HCMensual()
    + HC HCAnual()
}

class DatosActividades {
    - TipoDeConsumo tipoDeConsumo
    - int valor
    - String periodicidad
    - String periodoImputacion

    + TipoDeConsumo encontrarTipo(String tipo)
}

class TipoDeConsumo {
  - Unidad unidad;
  - Actividad actividad;
  - Alcance alcance;
  - FactorEmision fe;

  + void cargarFactorEmision(FactorEmision fe)
} 

DatosActividades --> "1" TipoDeConsumo

class NoCoincidenUnidadesFEYTC extends RuntimeException {}

class TipoDeConsumoFactory{
  + buildTipoDeConsumo(string tipo)
}

TipoDeConsumoFactory --> TipoDeConsumo

TipoDeConsumo --> NoCoincidenUnidadesFEYTC

class FactorEmision {
  - int valor;
  - Unidad unidad;

  + FactorEmision(int valor, Unidad unidad)
  + Unidad getUnidad() 
}

enum Unidad {
    M3,
    LT,
    KG,
    KWH,
    KM
}

enum Alcance {
  DIRECTAS, 
  INDIRECTAS_ELECTRICIDAD, 
  INDIRECTAS_EXTERNAS
}

enum Actividad {
  COMBUSTION_FIJA, 
  COMBUSTION_MOVIL, 
  ELECTRICIDAD, 
  LOGISTICA_PRODUCTOS_RESIDUOS
}

TipoDeConsumo --> "1" Alcance
TipoDeConsumo --> "1" Unidad
TipoDeConsumo --> "1" Actividad
TipoDeConsumo --> "1" FactorEmision

class Sector{
    - Organizacion orgAlaQuePertenezco
    - List<Miembro> miembros
    - List<Miembro> miembrosParaAceptar

    + boolean containsMiembro(miembro)
    + void agregarMiembro(miembro)
    + boolean containsMiembroParaAceptar(miembro)
    + void agregarMiembroParaAceptar(miembro)
    + void sacarMiembroParaAceptar(miembro)
    + double combustibleConsumidoTransporteMiembros()
}

class Miembro {
    - String nombre
    - String apellido
    - TipoDeDocumento tipo
    - Integer nroDocumento
    - Sector sectorDondeTrabaja
    - List<Trayecto> trayectos

    + void registrarTrayecto(trayecto)
    + void vincularTrabajadorConOrg(organizacion, sector)
    + HC calculoHCPersonal(FactorEmision fe)
}

enum TipoDeDocumento {
    DNI,
    LE,
    LC,
    CI
}

Miembro --> "1" TipoDeDocumento
Organizacion --> "1" TipoOrganizacion
Organizacion --> "1" ClasificacionOrganizacion
Organizacion --> "*" Sector
Organizacion --> "*" DatosActividades

Sector --> "1" Organizacion
Sector --> "*" Miembro
Miembro ---> "1" Sector


class Distancia {
  - double valor
  - UnidadDeDistancia unidad

  + double valorEnMetros()
}

enum UnidadDeDistancia {
  KM,
  MTS
} 

Distancia --> UnidadDeDistancia

class Trayecto{
    - List<Tramo> tramos
    - Miembro owner

    + void agregarTramo(tramo)
    + Distancia distanciaTotal(void)
    + List<Miembro> miembros()
}

class TrayectoCompartido extends Trayecto {
  - List<Miembro> miembros
  - List<Tramo> tramos
  - Miembro owner

  + void validacionTrayectoCompartido(Tramo tramo)
  + List<Miembro> miembros()
  + void agregarTramo(Tramo tramo)
}

TrayectoCompartido --> "*" Miembro
TrayectoCompartido --> "*" Tramo

class Tramo{
    - MedioDeTransporte medioDeTransporte

    + Distancia distancia(void)
    + boolean admiteTrayectoCompartido()
}

interface MedioDeTransporte {
    + Distancia getDistancia(void)
    + boolean admiteTrayectoCompartido()
    + double getCombustibleConsumidoPorKM()
}

class TransportePublico implements MedioDeTransporte{
  - Parada paradaInicio;
  - Parada paradaFin;
  - TipoTransportePublico tipo;
  - Linea linea;
  
  + Distancia getDistancia()
  + boolean admiteTrayectoCompartido()
  + double getCombustibleConsumidoPorKM()
}

class VehiculoParticular extends MedioNoPublico {

  - Ubicacion direccionInicio
  - Ubicacion direccionFin
  - TipoDeVehiculo tipoVehiculo
  - TipoDeCombustible tipoCombustible

  + boolean admiteTrayectoCompartido()
  + double getCombustibleConsumidoPorKM()
}

class ServicioContratado extends MedioNoPublico{
  -Ubicacion direccionInicio
  - Ubicacion direccionFin
  - TipoServicioContratado tipo

  + boolean admiteTrayectoCompartido()
  + double getCombustibleConsumidoPorKM()
}


abstract class MedioNoPublico implements MedioDeTransporte {
  + Ubicacion getDireccionInicio()
  + Ubicacion getDireccionFin()
  + Distancia getDistancia()
  + boolean admiteTrayectoCompartido()
}

class Bicicleta extends MedioNoPublico{
  - Ubicacion direccionInicio;
  - Ubicacion direccionFin;

  + double getCombustibleConsumidoPorKM()
}


class Pie extends MedioNoPublico {
    - Ubicacion direccionInicio
    - Ubicacion direccionFin

    + double getCombustibleConsumidoPorKM()
}

enum TipoDeVehiculo{
    MOTO
    AUTO
    CAMIONETA
}

enum TipoDeCombustible{
    GNC,
    NAFTA,
    ELECTRICO,
    GASOIL
}

enum TipoTransportePublico{
    TREN
    SUBTE
    COLECTIVO
}

class Parada{
    - String nombre
    - Int distAproximaParada

    + int getDistAproximaParada(void)
}

class Linea {

  - String nombre
  - List<Parada> paradas
  - TipoTransportePublico tipo
  + boolean isTipo(TipoTransportePublico otroTipo)
  + boolean containsParada(Parada parada)
  + void agregarParada(Parada parada)
  + int distanciaEntreParadas(Parada paradaInicio, Parada paradaFin)
}

class TipoServicioContratado{
    - String nombre
}

ServicioContratado --> "1" TipoServicioContratado

Miembro  "1" --> "*" Trayecto
Trayecto --> "*" Tramo
Tramo --> "1" MedioDeTransporte
TransportePublico --> "1" TipoTransportePublico
TransportePublico --> "1" Linea
VehiculoParticular --> "1" TipoDeVehiculo
VehiculoParticular --> "1" TipoDeCombustible
TransportePublico --> "2" Parada
Linea --> "*" Parada
Linea --> "1" TipoTransportePublico


class Contrasenia {
    - List<Validacion> validaciones;

    + validarContrasenia(String contrasenia);
    + setValidaciones(Validacion ...validaciones);
}

class RuntimeException{}

interface Validacion {
    + boolean condicion(String contrasenia)
    + PasswordException error()
}

class PasswordException extends RuntimeException_ {
    + PasswordException()
}

class RuntimeException_ {}

Contrasenia "1" --> "*" Validacion
Validacion --> PasswordException



class ValidacionLongitud implements Validacion{
}

class ValidacionMayusculas implements Validacion{
}

class ValidacionMinusculas implements Validacion {
}

class ValidacionNumeros implements Validacion {
}

class ValidacionContraseniaComun implements Validacion {
}

class Administrador {
    - String nombreDeUsuario
    - Contrasenia contrasenia
}

Administrador "1" --> "1" Contrasenia

class Ubicacion {
  - String calle
  - int altura
  - Localidad localidad
  - ServicioGeoDds apiClient
  + Distancia calcularDistanciaA(Ubicacion otraUbicacion)
}

class Localidad {
  - int id
  - String nombre
  - ServicioGeoDds apiClient
  - Municipio municipio
}

class Municipio implements SectorTerritorial {
  - int id
  - String nombre
  - ServicioGeoDds apiClient
  - Provincia provincia

  + List<Organizacion> orgsDentroDelSector()
}

class Provincia implements SectorTerritorial {
  - int id
  - String nombre
  - ServicioGeoDds apiClient
  - Pais pais

  + List<Organizacion> orgsDentroDelSector()
}

class Pais {
  - int id
  - String nombre
  - ServicioGeoDds apiClient
}

Ubicacion --> "1" Localidad
Localidad --> "1" Municipio
Municipio --> "1" Provincia
Provincia --> "1" Pais
Organizacion --> "1" Ubicacion
Organizacion --> "1" Ubicacion
MedioNoPublico --> "*" Ubicacion
ServicioContratado --> "*" Ubicacion
VehiculoParticular --> "*" Ubicacion
Bicicleta --> "*" Ubicacion
Pie --> "*" Ubicacion


' interface RetrofitGeoDds {
'   + Call<List<Pais>> paises(String token, int offset);
'   + Call<List<Provincia>> provincias(String token, int offset);
'   + Call<List<Provincia>> provincias(String token, int offset, int paisId);
'   + Call<List<Localidad>> localidades(String token, int offset);
'   + Call<List<Localidad>> localidades(String token, int offset, int municipioId);
'   + Call<List<Municipio>> municipios(String token, int offset);
'   + Call<List<Municipio>> municipios(String token, int offset, int provinciaId);
'   + Call<Distancia> distancia(String token, int localidadOrigenId, String calleOrigen, int alturaOrigen, int localidadDestinoId, String calleDestino, int alturaDestino);
' }

class ServicioGeoDds {
  - ServicioGeoDds instancia
  - String urlAPI
  - Retrofit retrofit
  - String apiKey

  + ServicioGeoDds getInstancia()
  + distanciaEntreUbicaciones(Ubicacion origen, Ubicacion destino)
  + void validarId(Integer id, String mensajeError)
  + int verificarNombrePais(String nombrePais)
  + int verificarNombreProvincia(String nombreProvincia)
  + int verificarNombreMunicipio(String nombreMunicipio)
  + int verificarNombreLocalidad(String nombreLocalidad)
}

ServicioGeoDds --> "1" RetrofitGeoDds
Ubicacion --> "1" ServicioGeoDds
Localidad --> "1" ServicioGeoDds


class AgenteSectorial{
  - SectorTerritorial sectorTerritorial

  + HC hc()
}

interface SectorTerritorial {
  + List<Organizacion> orgsDentroDelSector()
}

AgenteSectorial --> SectorTerritorial


class RepoOrganizaciones {
  - List<Organizacion> organizaciones

  + void agregarOrganizacion(Organizacion organizacion)
  + List<Organizacion> getOrganizaciones()
  + Boolean inMunicipio(Municipio municipio)
  + Boolean inProvincia(Provincia provincia)
}

RepoOrganizaciones --> Organizacion
Municipio --> RepoOrganizaciones
Provincia --> RepoOrganizaciones


enum UnidadHC {
  gCO2,
  kgCO2,
  tnCO2
}

class HC {
  - double valor
  - UnidadHC unidad

  + double enGCO2()
  + double enKgCO2()
  + double enTnCO2()
}

HC --> UnidadHC
Organizacion --> HC
Miembro --> HC
AgenteSectorial --> HC
class ValidadorDatoDeContacto {
  + boolean emailEsValido(String email)
  + boolean whatsAppEsValido(String whatsapp)
  + void validarEmail(String email)
  + void validarWhatsapp(String whatsapp)
}

' ENVÍO DE NOTIFICACIONES

interface Job {
    + execute()
}

class ObserverNotificaciones implements Job
{
  - notificador
}

class Notificador
{
  - organizaciones
  + getInstancia()
  + agregarOrganizacion(Organizacion ... organizaciones)
  + notificarATodos()
}

interface NotificacionAdapter
{
  + enviar()
}

class WhatsAppAdapter implements NotificacionAdapter {}

class EmailAdapter implements NotificacionAdapter {}

class Notificacion
{
  - notificacionAdapter
  + enviar()
}

class Contacto {
  - email
  - whatsapp
  - suscripciones
  + agregarSuscripcion()
}

ObserverNotificaciones --> Notificador
Notificacion --> "1" NotificacionAdapter
Notificador --> "*" Organizacion
Contacto --> "*" Notificacion
Organizacion --> "*" Contacto
Contacto --> ValidadorDatoDeContacto

@enduml